  UNISWAP_V3_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
  SUSHISWAP_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/sushiswap/exchange"
  AAVE_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/aave/protocol-v2"
  CURVE_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/curvefi/curve"
  BALANCER_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2"
  COMPOUND_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/compound-finance/compound-v2"
  ARBITRUM_UNISWAP_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3-arbitrum"
  DEFI_SAFETY_API = "https://api.defisafety.com/protocols"
